[package]
name = "spotify-pocket"
version = "0.1.0"
description = "A Tauri App"
authors = ["Rodrigo Gollo"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "spotify_pocket_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-shell = "2.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
axum = "0.7.7"
tokio = "1.40.0"
rand = "0.8.5"
base64 = "0.22.1"
tauri-plugin-store = "2"
dotenvs = "0.1.0"
